package org.example.lab3.dto;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Past;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDate;

/**
 * DTO for creating or updating an Author.
 * Does not include id as it's generated by the server.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class AuthorCreateUpdateDto {
    @NotBlank
    private String name;
    @NotNull
    @Past
    private LocalDate birthDate;
}
